export const seasons = [{
    "season":"1",
    "league": {
        "name": "21-26 Nisan Ligi",
        "groups": [
            {
                "name": "A Grubu",
                "teams": [
                    {
                        "order": "1",
                        "name": "burcing",
                        "matchPlayed": "6",
                        "win": "4",
                        "draw": "2",
                        "lost": "0",
                        "goalScored": "12",
                        "goalConceded": "2",
                        "average": "10",
                        "point": "14"
                    },
                    {
                        "order": "2",
                        "name": "izzetpasa",
                        "matchPlayed": "6",
                        "win": "2",
                        "draw": "3",
                        "lost": "1",
                        "goalScored": "10",
                        "goalConceded": "7",
                        "average": "3",
                        "point": "9"
                    },
                    {
                        "order": "3",
                        "name": "gknozd",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "3",
                        "lost": "2",
                        "goalScored": "14",
                        "goalConceded": "15",
                        "average": "-1",
                        "point": "6"
                    },
                    {
                        "order": "4",
                        "name": "onrmdc",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "0",
                        "lost": "5",
                        "goalScored": "22",
                        "goalConceded": "10",
                        "average": "-12",
                        "point": "3"
                    }
                ],
                matches: [
                    {"order": 1,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "burcing",
                     "team2_name": "izzetpasa",
                     "team1_score": 2,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 2,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 1,
                     "team2_score": 4,
                     "match_played": true
                    },
                    {"order": 3,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "onrmdc",
                     "team2_name": "izzetpasa",
                     "team1_score": 3,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 4,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "burcing",
                     "team1_score": 1,
                     "team2_score": 2,
                     "match_played": true
                    },
                    {"order": 5,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "onrmdc",
                     "team2_name": "burcing",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 6,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 7,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 8,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 9,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 10,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "gknozd",
                     "team2_name": "izzetpasa",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 11,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 12,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    }
                    ]
            },
            {
                "name": "B Grubu",
                "teams": [
                    {
                        "order": "1",
                        "name": "burcing",
                        "matchPlayed": "6",
                        "win": "4",
                        "draw": "2",
                        "lost": "0",
                        "goalScored": "12",
                        "goalConceded": "2",
                        "average": "10",
                        "point": "14"
                    },
                    {
                        "order": "2",
                        "name": "izzetpasa",
                        "matchPlayed": "6",
                        "win": "2",
                        "draw": "3",
                        "lost": "1",
                        "goalScored": "10",
                        "goalConceded": "7",
                        "average": "3",
                        "point": "9"
                    },
                    {
                        "order": "3",
                        "name": "gknozd",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "3",
                        "lost": "2",
                        "goalScored": "14",
                        "goalConceded": "15",
                        "average": "-1",
                        "point": "6"
                    },
                    {
                        "order": "4",
                        "name": "onrmdc",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "0",
                        "lost": "5",
                        "goalScored": "22",
                        "goalConceded": "10",
                        "average": "-12",
                        "point": "3"
                    }
                ],
                matches: [
                    {"order": 1,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "burcing",
                     "team2_name": "izzetpasa",
                     "team1_score": 2,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 2,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 1,
                     "team2_score": 4,
                     "match_played": true
                    },
                    {"order": 3,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "onrmdc",
                     "team2_name": "izzetpasa",
                     "team1_score": 3,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 4,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "burcing",
                     "team1_score": 1,
                     "team2_score": 2,
                     "match_played": true
                    },
                    {"order": 5,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "onrmdc",
                     "team2_name": "burcing",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 6,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 7,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 8,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 9,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 10,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "gknozd",
                     "team2_name": "izzetpasa",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 11,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 12,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    }
                    ]
            },
            {
                "name": "C Grubu",
                "teams": [
                    {
                        "order": "1",
                        "name": "burcing",
                        "matchPlayed": "6",
                        "win": "4",
                        "draw": "2",
                        "lost": "0",
                        "goalScored": "12",
                        "goalConceded": "2",
                        "average": "10",
                        "point": "14"
                    },
                    {
                        "order": "2",
                        "name": "izzetpasa",
                        "matchPlayed": "6",
                        "win": "2",
                        "draw": "3",
                        "lost": "1",
                        "goalScored": "10",
                        "goalConceded": "7",
                        "average": "3",
                        "point": "9"
                    },
                    {
                        "order": "3",
                        "name": "gknozd",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "3",
                        "lost": "2",
                        "goalScored": "14",
                        "goalConceded": "15",
                        "average": "-1",
                        "point": "6"
                    },
                    {
                        "order": "4",
                        "name": "onrmdc",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "0",
                        "lost": "5",
                        "goalScored": "22",
                        "goalConceded": "10",
                        "average": "-12",
                        "point": "3"
                    }
                ],
                matches: [
                    {"order": 1,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "burcing",
                     "team2_name": "izzetpasa",
                     "team1_score": 2,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 2,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 1,
                     "team2_score": 4,
                     "match_played": true
                    },
                    {"order": 3,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "onrmdc",
                     "team2_name": "izzetpasa",
                     "team1_score": 3,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 4,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "burcing",
                     "team1_score": 1,
                     "team2_score": 2,
                     "match_played": true
                    },
                    {"order": 5,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "onrmdc",
                     "team2_name": "burcing",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 6,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 7,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 8,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 9,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 10,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "gknozd",
                     "team2_name": "izzetpasa",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 11,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 12,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    }
                    ]
            },
            {
                "name": "D Grubu",
                "teams": [
                    {
                        "order": "1",
                        "name": "burcing",
                        "matchPlayed": "6",
                        "win": "4",
                        "draw": "2",
                        "lost": "0",
                        "goalScored": "12",
                        "goalConceded": "2",
                        "average": "10",
                        "point": "14"
                    },
                    {
                        "order": "2",
                        "name": "izzetpasa",
                        "matchPlayed": "6",
                        "win": "2",
                        "draw": "3",
                        "lost": "1",
                        "goalScored": "10",
                        "goalConceded": "7",
                        "average": "3",
                        "point": "9"
                    },
                    {
                        "order": "3",
                        "name": "gknozd",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "3",
                        "lost": "2",
                        "goalScored": "14",
                        "goalConceded": "15",
                        "average": "-1",
                        "point": "6"
                    },
                    {
                        "order": "4",
                        "name": "onrmdc",
                        "matchPlayed": "6",
                        "win": "1",
                        "draw": "0",
                        "lost": "5",
                        "goalScored": "22",
                        "goalConceded": "10",
                        "average": "-12",
                        "point": "3"
                    }
                ],
                matches: [
                    {"order": 1,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "burcing",
                     "team2_name": "izzetpasa",
                     "team1_score": 2,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 2,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 1,
                     "team2_score": 4,
                     "match_played": true
                    },
                    {"order": 3,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "onrmdc",
                     "team2_name": "izzetpasa",
                     "team1_score": 3,
                     "team2_score": 3,
                     "match_played": true
                    },
                    {"order": 4,
                     "match_date": "17.05.2020 19:00",
                     "match_day": 1,
                     "team1_name": "gknozd",
                     "team2_name": "burcing",
                     "team1_score": 1,
                     "team2_score": 2,
                     "match_played": true
                    },
                    {"order": 5,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "onrmdc",
                     "team2_name": "burcing",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 6,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 7,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "gknozd",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 8,
                     "match_date": "18.05.2020 19:00",
                     "match_day": 2,
                     "team1_name": "izzetpasa",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 9,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 10,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "gknozd",
                     "team2_name": "izzetpasa",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 11,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "onrmdc",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    },
                    {"order": 12,
                     "match_date": "19.05.2020 19:00",
                     "match_day": 3,
                     "team1_name": "burcing",
                     "team2_name": "gknozd",
                     "team1_score": 0,
                     "team2_score": 0,
                     "match_played": false
                    }
                    ]
            }
        ]
    }
}];